In [1]:
# script to create a dataframe of random mock data.
import pandas
from faker import Factory
import random
from datetime import datetime
from datetime import date

faker = Factory.create()
status = 'created,delivered,returned'.split(',')

def date_between(d1, d2):
    f = '%b%d-%Y'
    return faker.date_time_between_dates(datetime.strptime(d1, f), datetime.strptime(d2, f))


def mockPCAPRecord():
    return {
#'id': faker.numerify('###'),  # random number eg:235533
            'posting_date': date_between('may19-2019', 'jan01-2021'),
            '50_prcntile_fwd_new': faker.numerify('##'),  # top n (n-percentile) order's latency numbers in seconds (randomly gen.) 
            '50_prcntile_fwd_cxl': faker.numerify('##'),
            '50_prcntile_fwd_mod': faker.numerify('##'),
            '50_prcntile_rev_new': faker.numerify('##'),
            '50_prcntile_rev_cxl': faker.numerify('##'),
            '50_prcntile_rev_mod': faker.numerify('##'),
            "90_prcntile_fwd_new": faker.numerify('##'),
            "90_prcntile_fwd_cxl": faker.numerify('##'),
            "90_prcntile_fwd_mod": faker.numerify('##'),
            "90_prcntile_rev_new": faker.numerify('##'),
            "90_prcntile_rev_cxl": faker.numerify('##'),
            "90_prcntile_rev_mod": faker.numerify('##'),
            "99_prcntile_fwd_new": faker.numerify('##'),
            "99_prcntile_fwd_cxl": faker.numerify('##'),
            "99_prcntile_fwd_mod": faker.numerify('##'),
            "99_prcntile_rev_new": faker.numerify('##'),
            "99_prcntile_rev_cxl": faker.numerify('##'),
            "99_prcntile_rev_mod": faker.numerify('##'),
            "avg_fwd_new": faker.numerify('##'),
            "avgfwd_cxl": faker.numerify('##'),
            "avg_fwd_mod": faker.numerify('##'),
            "avg_rev_new": faker.numerify('##'),
            "avg_rev_cxl": faker.numerify('##'),
            "avg_rev_mod": faker.numerify('##'),
            "posting_updated": date.today()        
             }

example_dummy_data = pandas.DataFrame([mockPCAPRecord() for _ in range(1000)])
example_dummy_data.sample(5)

,posting_date,50_prcntile_fwd_new,50_prcntile_fwd_cxl,50_prcntile_fwd_mod,50_prcntile_rev_new,50_prcntile_rev_cxl,50_prcntile_rev_mod,90_prcntile_fwd_new,90_prcntile_fwd_cxl,90_prcntile_fwd_mod,...,99_prcntile_rev_new,99_prcntile_rev_cxl,99_prcntile_rev_mod,avg_fwd_new,avgfwd_cxl,avg_fwd_mod,avg_rev_new,avg_rev_cxl,avg_rev_mod,posting_updated
721,2019-09-07 18:16:29,34,20,08,15,02,20,49,95,55,...,97,04,73,10,79,63,92,90,28,2021-02-03
737,2020-09-10 13:02:20,44,76,73,37,89,54,53,08,56,...,74,95,85,96,54,32,04,35,82,2021-02-03
754,2020-10-17 01:36:58,87,35,25,87,75,73,38,19,17,...,95,54,23,41,80,87,82,78,99,2021-02-03
720,2020-01-03 22:34:05,02,12,50,68,90,71,96,58,40,...,90,79,38,48,78,39,99,69,71,2021-02-03
142,2019-08-20 15:40:21,42,01,73,37,26,02,80,98,90,...,22,70,27,21,95,47,90,34,08,2021-02-03

In [2]:
df=example_dummy_data;
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   posting_date         1000 non-null   datetime64[ns]
 1   50_prcntile_fwd_new  1000 non-null   object
 2   50_prcntile_fwd_cxl  1000 non-null   object
 3   50_prcntile_fwd_mod  1000 non-null   object
 4   50_prcntile_rev_new  1000 non-null   object
 5   50_prcntile_rev_cxl  1000 non-null   object
 6   50_prcntile_rev_mod  1000 non-null   object
 7   90_prcntile_fwd_new  1000 non-null   object
 8   90_prcntile_fwd_cxl  1000 non-null   object
 9   90_prcntile_fwd_mod  1000 non-null   object
 10  90_prcntile_rev_new  1000 non-null   object
 11  90_prcntile_rev_cxl  1000 non-null   object
 12  90_prcntile_rev_mod  1000 non-null   object
 13  99_prcntile_fwd_new  1000 non-null   object
 14  99_prcntile_fwd_cxl  1000 non-null   object
 15  99_prcntile_fwd_mod  1000 non-null   object
 16  99_prcntile_rev_new  1000 non-null   object
 17  99_prcntile_rev_cxl  1000 non-null   object
 18  99_prcntile_rev_mod  1000 non-null   object
 19  avg_fwd_new          1000 non-null   object
 20  avgfwd_cxl           1000 non-null   object
 21  avg_fwd_mod          1000 non-null   object
 22  avg_rev_new          1000 non-null   object
 23  avg_rev_cxl          1000 non-null   object
 24  avg_rev_mod          1000 non-null   object
 25  posting_updated      1000 non-null   object
dtypes: datetime64[ns](1), object(25)
memory usage: 203.2+ KB

In [3]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [4]:
df

,posting_date,50_prcntile_fwd_new,50_prcntile_fwd_cxl,50_prcntile_fwd_mod,50_prcntile_rev_new,50_prcntile_rev_cxl,50_prcntile_rev_mod,90_prcntile_fwd_new,90_prcntile_fwd_cxl,90_prcntile_fwd_mod,...,99_prcntile_rev_new,99_prcntile_rev_cxl,99_prcntile_rev_mod,avg_fwd_new,avgfwd_cxl,avg_fwd_mod,avg_rev_new,avg_rev_cxl,avg_rev_mod,posting_updated
0,2019-09-26 08:52:15,61,68,89,24,42,89,19,43,80,...,03,64,56,93,13,03,05,53,08,2021-02-03
1,2019-11-10 00:49:01,14,69,97,15,35,14,77,90,02,...,42,09,37,76,94,22,93,16,66,2021-02-03
2,2020-06-10 02:07:16,19,79,62,25,46,53,31,33,50,...,20,65,01,47,63,92,66,08,46,2021-02-03
3,2020-04-07 21:42:21,05,90,25,25,16,51,01,43,09,...,50,46,40,93,82,48,49,33,14,2021-02-03
4,2020-07-15 20:01:36,15,68,45,31,40,80,58,03,05,...,19,14,19,14,78,24,82,26,72,2021-02-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-03-26 13:01:58,03,21,46,48,56,93,38,59,48,...,91,63,82,22,03,17,05,02,45,2021-02-03
996,2019-07-18 19:36:02,75,76,62,89,00,72,83,63,90,...,19,63,34,00,40,29,36,40,71,2021-02-03
997,2020-07-09 20:15:00,94,28,65,95,72,76,10,11,71,...,65,21,40,49,67,58,16,16,09,2021-02-03
998,2019-09-17 15:19:54,06,06,16,17,89,62,94,40,57,...,06,41,38,98,15,01,49,02,81,2021-02-03
999,2020-06-07 17:11:34,92,25,81,37,57,79,21,94,67,...,39,80,26,76,21,23,60,71,32,2021-02-03

In [10]:
df[["posting_date"]]

           posting_date
0   2019-09-26 08:52:15
1   2019-11-10 00:49:01
2   2020-06-10 02:07:16
3   2020-04-07 21:42:21
4   2020-07-15 20:01:36
..                  ...
995 2020-03-26 13:01:58
996 2019-07-18 19:36:02
997 2020-07-09 20:15:00
998 2019-09-17 15:19:54
999 2020-06-07 17:11:34

[1000 rows x 1 columns]

In [8]:
# df['posting_date'].info() #This does not returna data frame.

AttributeError: 'Series' object has no attribute 'info'

In [12]:
df.loc[[2, 3, 4, 67]][["50_prcntile_fwd_new"]] #chaining loc

   50_prcntile_fwd_new
2                   19
3                   05
4                   15
67                  50

In [15]:
df.loc[[2, 3, 4, 67]].sample(2)

,posting_date,50_prcntile_fwd_new,50_prcntile_fwd_cxl,50_prcntile_fwd_mod,50_prcntile_rev_new,50_prcntile_rev_cxl,50_prcntile_rev_mod,90_prcntile_fwd_new,90_prcntile_fwd_cxl,90_prcntile_fwd_mod,...,99_prcntile_rev_new,99_prcntile_rev_cxl,99_prcntile_rev_mod,avg_fwd_new,avgfwd_cxl,avg_fwd_mod,avg_rev_new,avg_rev_cxl,avg_rev_mod,posting_updated
3,2020-04-07 21:42:21,05,90,25,25,16,51,01,43,09,...,50,46,40,93,82,48,49,33,14,2021-02-03
4,2020-07-15 20:01:36,15,68,45,31,40,80,58,03,05,...,19,14,19,14,78,24,82,26,72,2021-02-03

In [27]:
df['50_prcntile_fwd_new'].mode()

0    36
1    95
dtype: object